version: '3.8'

networks:
  microservice-email-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.3.0
    networks:
      - microservice-email-network
    ports:
      - "${DATABASE_HOST_PORT}:${DATABASE_DOCKER_PORT}"
    env_file:
      - env/mysql.env
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    networks:
      - microservice-email-network
    ports:
      - "${PHPMYADMIN_HOST_PORT}:${PHPMYADMIN_DOCKER_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - env/phpmyadmin.env

  microservice-email:
    image: esperanca98/microservice-email:latest
    networks:
      - microservice-email-network
    ports:
      - "${SERVER_HOST_PORT}:${SERVER_DOCKER_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - env/microservice-email.env
