version: '3.8'

networks:
  microservice-email-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: microservice-email-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_USER_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservice-email-network

volumes:
  postgres_data:
